# Generated by Django 5.1.2 on 2024-10-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("occupation", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("nominee", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "account_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("account_type", models.CharField(max_length=50)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("branch", models.CharField(max_length=50)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AccountApp.clients",
                    ),
                ),
            ],
        ),
    ]
