# Generated by Django 5.1.2 on 2024-11-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AccountApp", "0002_rename_clients_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "branch_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("branch_name", models.CharField(max_length=50)),
                ("branch_location", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=250)),
                (
                    "transaction_limit",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("interest_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("monthly_fee", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name="client",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="nominee",
        ),
        migrations.AddField(
            model_name="client",
            name="client_identification_document_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="client_identification_document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="nominee_identification_document_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="nominee_identification_document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="nominee_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="nominee_relation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="residency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="branch_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AccountApp.branch",
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "client_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AccountApp.client",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AccountApp.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teller",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=250)),
                (
                    "branch_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AccountApp.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=250)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "employee_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AccountApp.teller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("transaction_type", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField()),
                (
                    "from_account_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_account",
                        to="AccountApp.account",
                    ),
                ),
                (
                    "to_account_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_account",
                        to="AccountApp.account",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BankAccount",
        ),
    ]
