# Generated by Django 5.1.2 on 2024-11-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "AccountApp",
            "0003_branch_product_rename_firstname_client_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="teller",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
