# Generated by Django 5.1.2 on 2024-11-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AccountApp", "0004_alter_teller_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="interest_rate",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="monthly_fee",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="transaction_limit",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
